# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.0
          cache: "yarn"
      - run: yarn install
      - run: yarn workspace @tender/shared build
      - run: yarn workspace @tender/shared lint
      - run: yarn workspace @tender/shared pretty
      - run: yarn workspace @tender/app build
      - run: yarn workspace @tender/app lint
      - run: yarn workspace @tender/app pretty
      - run: yarn workspace @tender/landing build
      - run: yarn workspace @tender/landing lint
      - run: yarn workspace @tender/landing pretty
